name: CI

on:
  pull_request:
  push:
    branches:
      - main 

concurrency:
  group: ci-${{ github.head_ref }}-${{ github.event_name }}
  cancel-in-progress: true

# Recommended here: https://github.com/bazelbuild/bazelisk/issues/88#issuecomment-625178467
env:
  BAZELISK_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  OPAL_RPC_CREDENTIALS: ${{ secrets.OPAL_RPC_CREDENTIALS }}  

jobs:
  build_macos:
    runs-on:
      - "self-hosted"
      - "os=macos"
      - "arch=arm64"
      - "os_distribution=sonoma"
      - "os_version=14"
      - "revision=c12cc4655257fcf7da86fe06e87542b7e6814a1f"
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - name: Set up authentication
        shell: bash
        run: "cp .bazelrc.ci .bazelrc.user"
      - name: Test
        run: |
          bazel test --test_output=errors --config=engflow --config=remote_macos_arm64 //...

  build_linux:
    runs-on:
      - "self-hosted"
      - "os=linux"
      - "arch=x64"
      - "engflow-container-image=docker://645088952840.dkr.ecr.eu-west-1.amazonaws.com/engflow-ci/debian11-dind-x64@sha256:a0f386162b6498b9220a33f33f158fd175d2873ddd6ed30ca67aa33915850e1e"
      - "engflow-pool=ci_sysbox_x64"
      - "engflow-runtime=sysbox-runc"
      - "engflow-runner-id=${{ github.repository_id }}_ci-runners-test-matrix_${{ github.run_id }}_${{ github.run_number }}_${{ github.run_attempt }}"
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        bazel-version: ["", "7.x", "last_rc"]
        include:
          - bazel-version: "last_rc"
            custom-bazelrc: ".bazelrc-9"
    env:
      USE_BAZEL_VERSION: ${{ matrix.bazel-version }}
      BAZELRC: ${{ matrix.custom-bazelrc }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up authentication
        shell: bash
        run: "cp .bazelrc.ci .bazelrc.user"
      - name: Test
        run: |
          bazel test --test_output=errors --config=engflow --config=remote_macos_arm64 //...

  # Imitate the BCR test in .bcr/presubmit.yml.
  # Keep in sync with configurations in .bcr/presubmit.yml. We cannot run
  # those tests in CI: they are post-release only. So we need to cover the
  # same configurations here.
  bcr_test_module_macos:
    runs-on:
      - "self-hosted"
      - "os=macos"
      - "arch=arm64"
      - "os_distribution=sonoma"
      - "os_version=14"
      - "revision=c12cc4655257fcf7da86fe06e87542b7e6814a1f"
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        bazel-version: ["7.*", "8.*", "9.*"]
    env:
      USE_BAZEL_VERSION: "${{ matrix.bazel-version }}"
    defaults:
      run:
        working-directory: "example/bzlmod"
    steps:
      - uses: actions/checkout@v4
      - name: Set up authentication
        shell: bash
        run: "cp .bazelrc.ci .bazelrc.user"
      - name: Run Gazelle
        run: "bazel run --config=engflow --config=remote_macos_arm64 //:gazelle"
      - name: Build
        run: "bazel build --config=engflow --config=remote_macos_arm64 //..."
      - name: Test
        run: "bazel test --config=engflow --config=remote_macos_arm64 //..."

  bcr_test_module_linux:
    runs-on:
      - "self-hosted"
      - "os=linux"
      - "arch=x64"
      - "engflow-container-image=docker://645088952840.dkr.ecr.eu-west-1.amazonaws.com/engflow-ci/debian11-dind-x64@sha256:a0f386162b6498b9220a33f33f158fd175d2873ddd6ed30ca67aa33915850e1e"
      - "engflow-pool=ci_sysbox_x64"
      - "engflow-runtime=sysbox-runc"
      - "engflow-runner-id=${{ github.repository_id }}_ci-runners-test-matrix_${{ github.run_id }}_${{ github.run_number }}_${{ github.run_attempt }}"
    strategy:
      fail-fast: false
      matrix:
        bazel-version: ["7.*", "8.*", "9.*"]
    timeout-minutes: 10
    env:
      USE_BAZEL_VERSION: ${{ matrix.bazel-version }}
    defaults:
      run:
        working-directory: "example/bzlmod"
    steps:
      - uses: actions/checkout@v4
      - name: Set up authentication
        shell: bash
        run: "cp .bazelrc.ci .bazelrc.user"
      - name: Run Gazelle
        run: "bazel run --config=engflow --config=remote_linux_x64 //:gazelle"
      - name: Build
        run: "bazel build --config=engflow --config=remote_linux_x64 //..."
      - name: Test
        run: "bazel test --config=engflow --config=remote_linux_x64 //..."

  test-indexers:
    runs-on:
      - "self-hosted"
      - "os=linux"
      - "arch=x64"
      - "engflow-container-image=docker://645088952840.dkr.ecr.eu-west-1.amazonaws.com/engflow-ci/debian11-dind-x64@sha256:a0f386162b6498b9220a33f33f158fd175d2873ddd6ed30ca67aa33915850e1e"
      - "engflow-pool=ci_sysbox_x64"
      - "engflow-runtime=sysbox-runc"
      - "engflow-runner-id=${{ github.repository_id }}_ci-runners-test-matrix_${{ github.run_id }}_${{ github.run_number }}_${{ github.run_attempt }}"
    timeout-minutes: 15
    steps:
    - uses: actions/checkout@v4
    - name: Set up authentication
      shell: bash
      run: "cp .bazelrc.ci .bazelrc.user"
    - name: Install Conan
      run: |
        python3 -m pip install --upgrade pip
        pip install conan
    - name: Execute manual integration tests
      run: bazel test --test_output=errors --config=engflow --config=remote_linux_x64 //index:integration_tests

  test-e2e:
    runs-on:
      - "self-hosted"
      - "os=linux"
      - "arch=x64"
      - "engflow-container-image=docker://645088952840.dkr.ecr.eu-west-1.amazonaws.com/engflow-ci/debian11-dind-x64@sha256:a0f386162b6498b9220a33f33f158fd175d2873ddd6ed30ca67aa33915850e1e"
      - "engflow-pool=ci_sysbox_x64"
      - "engflow-runtime=sysbox-runc"
      - "engflow-runner-id=${{ github.repository_id }}_ci-runners-test-matrix_${{ github.run_id }}_${{ github.run_number }}_${{ github.run_attempt }}"
    timeout-minutes: 15
    steps:
    - uses: actions/checkout@v4  
    - name: Set up authentication
      shell: bash
      run: "cp .bazelrc.ci .bazelrc.user"
    - name: Execute end to end tests
      run: bash .github/workflows/test_e2e.sh
          
  license-headers:
    runs-on:
      - "self-hosted"
      - "os=linux"
      - "arch=x64"
      - "engflow-container-image=docker://645088952840.dkr.ecr.eu-west-1.amazonaws.com/engflow-ci/debian11-dind-x64@sha256:a0f386162b6498b9220a33f33f158fd175d2873ddd6ed30ca67aa33915850e1e"
      - "engflow-pool=ci_sysbox_x64"
      - "engflow-runtime=sysbox-runc"
      - "engflow-runner-id=${{ github.repository_id }}_ci-runners-test-matrix_${{ github.run_id }}_${{ github.run_number }}_${{ github.run_attempt }}"
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - run: ./scripts/license_check.sh 
