name: Generate header mapping index

permissions:
  contents: write
  pull-requests: write

on:
  workflow_dispatch:
  schedule:
    # Runs at 03:00 AM, on day 1 of the month
    - cron: "0 3 1 * *"
jobs:
  build-plan:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6 (2026-09-23)
      - uses: coursier/cache-action@95e5b1029b6b86e7bac033ee44a0697d8a527d2d # v8 (2026-09-23)
      - uses: coursier/setup-action@3174df5c784a0c8724f06b7924b849551c40c39e # v3 (2026-09-23)
        with:
          apps: scala

      # Reuse already resolved info if available
      - uses: actions/cache@caa296126883cff596d87d8935842f9db880ef25 # v5 (2026-09-23)
        with:
          path: .cache/
          key: gen-mappings-indexer-cache

      - name: Generate mappings
        run: bazel run //index/internal/bcr/indexer --  \
          --output-mappings=$PWD/language/cc/bzldep-index.json \
          --recompute-unresolved \
          --cache-dir=$PWD/.cache \
          -v

      - name: Create PR
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          branchName="cron/update-index/$(date +%Y-%m-%d)"

          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git checkout -b $branchName
          git add ./language/cc/bzldep-index.json

          if git diff --cached --quiet; then
            echo "No changes to the index file, skipping PR creation"
            exit 0
          fi

          git commit -m "Automated update of headers index based on bazel-central-registry"
          git push origin $branchName

          gh pr create \
            --base=main \
            --head=$branchName \
            --title='[Bot] Update bazel-central-registry headers index' \
            --fill
